### ISSUE TITLE
OpenInmageR installation error

### ISSUE THREAD

**Issue by nitsourish** [mlampros/OpenImageR#1]
Compilation failed in Windows machine(with R version 3.2.2) even after installing Rtools and Rcpp.Is this package not ready for Windows OS?

**Comment by mlampros** [comment]
nitsourish, 
I'm sorry for the delayed answer. OpenImageR supports all OS platforms, have a look at https://cran.r-project.org/web/checks/check_results_OpenImageR.html for the package check results. The only exception is the r-oldrel-windows-ix86+x86_64 version. In case that you don't have the r-oldrel-windows version installed make sure that you have a recent version of RcppArmadillo (>= 0.7) and/or a latest GCC (GCC >= 4.9.0).
