### ISSUE TITLE
ignore values 

### ISSUE THREAD

**Issue by dschneiderch** [mlampros/OpenImageR#10]
i'm trying to use edge_detection() to detect snow line in a satellite image but I would like to ignore pixels classified as clouds or water. when i tried to set clouds or water to NA there is an error. i would only like to detect the edge between snow cover and bare ground. Is there another way to ignore a value in the detection algorithm?

**Comment by mlampros** [comment]
@dschneiderch I'm sorry for the late reply, 

the fact is that the *edge_detection()* function can not handle missing values that's why you receive the error. 
Would you mind sharing a reproducible example to attempt to adjust the function for your task?

**Comment by mlampros** [comment]
I close the issue for now, feel free to re-open it.
