### ISSUE TITLE
Error in documentation of rotateImage angle argument

### ISSUE THREAD

**Issue by dslate** [mlampros/OpenImageR#11]
In the section in the reference manual for the rotateImage function in OpenImageR version 1.1.2, the angle argument is described as "specifies the number of radians".  In fact angle is interpreted as degrees, not radians.

**Comment by mlampros** [comment]
@dslate thanks for making me aware of this error, I'll fix it tomorrow (the documentation of the [roteteFixed](https://github.com/mlampros/OpenImageR/blob/master/R/open_image_rscript.R#L633-L639) function too).
