### ISSUE TITLE
superpixels hangs on selected images

### ISSUE THREAD

**Issue by mbask** [mlampros/OpenImageR#17]
Hello,
running `superpixels` R hangs indefinitely when fed with selected images.
A reproducible example with one such image follows:
```
library(OpenImageR)
image_m <- structure(c(66, 60, 53, 45, 38, 34, 33, 35, 38, 42, 45, 47, 49, 
                       72, 67, 60, 53, 46, 41, 39, 40, 41, 43, 44, 44, 45, 78, 74, 69, 
                       62, 55, 50, 48, 46, 45, 44, 42, 39, 38, 82, 80, 76, 71, 65, 60, 
                       56, 52, 48, 43, 38, 32, 28, 85, 84, 81, 77, 71, 66, 61, 56, 49, 
                       40, 30, 22, 16, 85, 85, 83, 79, 74, 68, 62, 54, 45, 33, 21, 9, 
                       2, 83, 83, 81, 77, 71, 64, 57, 49, 38, 25, 11, 0, 0, 79, 80, 
                       77, 72, 65, 57, 49, 41, 31, 19, 6, 0, 0, 74, 75, 72, 66, 57, 
                       48, 40, 34, 28, 22, 13, 4, 0, 68, 70, 67, 60, 49, 39, 33, 32, 
                       34, 37, 37, 33, 28, 62, 65, 62, 54, 42, 32, 29, 36, 50, 66, 77, 
                       81, 78, 54, 59, 57, 48, 35, 26, 27, 44, 72, 104, 129, 141, 139, 
                       46, 52, 51, 42, 29, 21, 28, 54, 96, 143, 181, 201, 200, 38, 45, 
                       45, 37, 25, 18, 29, 63, 116, 174, 222, 248, 248, 31, 38, 39, 
                       33, 23, 19, 34, 72, 129, 192, 243, 255, 255, 28, 34, 36, 31, 
                       24, 25, 41, 79, 134, 194, 244, 255, 255, 28, 34, 35, 33, 30, 
                       33, 50, 84, 132, 184, 227, 253, 255), .Dim = c(13L, 17L), .Dimnames = list(
                         NULL, c("V1", "V2", "V3", "V4", "V5", "V6", "V7", "V8", "V9", 
                                 "V10", "V11", "V12", "V13", "V14", "V15", "V16", "V17")))
OpenImageR::superpixels(
  image_m,
  method = "slic",
  superpixel = 5,
  compactness = 30,
  return_slic_data = TRUE,
  return_labels    = TRUE,
  write_slic       = "",
  verbose          = TRUE)
```
In addition, when the same image segmentation is embedded in a Shiny application then a `double free or corruption (out)` error sometimes appears.

R 4.0.1, OpenImageR 1.1.7.

Thank you.

**Comment by mlampros** [comment]
hi @mbask, I'm sorry for the late reply and thanks for making me aware of this issue.

I took a look to the [Rcpp code](https://github.com/mlampros/OpenImageR/blob/master/inst/include/OpenImageRheader.h#L1499) of the *OpenImageR::superpixels()* function and based on your parameter setting the segfault happens in the ported [slic-code-snippet](https://github.com/mlampros/OpenImageR/blob/master/inst/include/OpenImageRheader.h#L1553-L1554). I wish I could be of help here but this is beyond my capabilities. I ported the *slic* and *slico* algorithms and applied slight modifications to the internal code of the Authors to make it work for both RGB and grey imagery. 

My guess here is that the small number of superpixels that you use (5) combined with the small dimensions of your imagery (13 x 17 pixels) is the main cause of the segfault (the [STEP size](https://github.com/mlampros/OpenImageR/blob/master/inst/include/SLIC.h#L1388) - which is the square-root of the superpixels - becomes quite small). There are a few options if you want to avoid similar errors,

* you can **increase** the *superpixel* parameter

```R

res_m = OpenImageR::superpixels(input_image = image_m,
                                method = "slic",
                                superpixel = 10,
                                compactness = 30,
                                return_slic_data = TRUE,
                                return_labels    = TRUE,
                                write_slic       = "",
                                verbose          = TRUE)

```

* you can **resize** (upscale) the image before using the *superpixels* function

```R

image_resz = OpenImageR::resizeImage(image_m, width = 20, height = 25, method = 'bilinear')
# OpenImageR::imageShow(image_resz)

res_m = OpenImageR::superpixels(input_image = image_resz,
                                method = "slic",
                                superpixel = 5,
                                compactness = 30,
                                return_slic_data = TRUE,
                                return_labels    = TRUE,
                                write_slic       = "",
                                verbose          = TRUE)

```

* you can increase the dimensions by using **padding** 

```R

image_pd = OpenImageR::padding(input_data = image_m, new_rows = 20, new_cols = 25, fill_value = 0)
# dim(image_pd$data)
im_pd = image_pd$data

# OpenImageR::imageShow(im_pd)

res_m = OpenImageR::superpixels(input_image = im_pd,
                                method = "slic",
                                superpixel = 5,
                                compactness = 20,
                                return_slic_data = TRUE,
                                return_labels    = TRUE,
                                write_slic       = "",
                                verbose          = TRUE)

```

**Comment by mbask** [comment]
Hello @mlampros! 

Thank you for your comments and examples. I see your point and reckon the best way to avoid the issue may be to increase the resolution of the original image as much as possible in order to meet a "safety threshold", before passing it to `superpixels`. I will test if 625 pixels (25 x 25) threshold is enough to avoid R from hanging.
Thank you
