### ISSUE TITLE
imageShow

### ISSUE THREAD

**Issue by ArdalPekh** [mlampros/OpenImageR#18]
imageShow used to display grayscale images. However, currently it only displays RGB images and cannot display grayscale images.

**Comment by mlampros** [comment]
Hi @ArdalPekh and I'm sorry for the late reply.

The following works for me in *OpenImageR 1.1.7*. In which Operating System do you use the R package?


```R
file_path = system.file('tmp_images/car.png', package = 'OpenImageR')
file_path

im = OpenImageR::readImage(file_path)
dim(im)
[1] 166 249


# display 2-dimensional matrix
OpenImageR::imageShow(im)

# display the '.png' using the file-path by opening internally a shiny-application
OpenImageR::imageShow(file_path)
```
