### ISSUE TITLE
First tried HOG_apply in OpenImageR on Windows 10, using binary Windows library

### ISSUE THREAD

**Issue by ecoquant** [mlampros/OpenImageR#22]
Received following message:

> > > X1<- HOG_apply(object="./", cells=3, orientations=6, threads=4)
> 
> error: Mat::init(): size is fixed and hence cannot be changed
> Error in list_2array_convert(tmp_lst) : 
>   Mat::init(): size is fixed and hence cannot be changed
> > 

Question is what is the maximum number of files that HOG_apply can be used with in a directory?  I got it to work with 9 files, but when I tried 32 files I got the above message.

Windows 10 Pro build 19042.1288, R version 4.1.1.

**Comment by mlampros** [comment]
hi @ecoquant, 
is it possible that you add a reproducible example? 

It seems that you use as 'object' parameter a directory of images. I used 40 image files as input and I receive no errors,

```R

> res = HOG_apply(FOLDER_path, cells=3, orientations=6, threads=4)

time to complete : 0.01370692 secs 

> str(res)
List of 2
 $ files: chr [1:40] "10 (3rd copy).png" "10 (4th copy).png" "10 (5th copy).png" "10 (6th copy).png" ...
 $ hog  : num [1:40, 1:54] 0.00464 0.00464 0.00464 0.00464 0.00464 ...

```

**Comment by ecoquant** [comment]
I will determine the actual limit and may send example. That's contingent
upon solving another problem: Understanding the format of output from HOG.
I don't know if the vector is organized so orientation bins are adjacent
and then these are grouped by cells, or some other order. I also don't know
if bin contributions are weighted by gradient strength. I looked at
SimpleCV but it is unhelpful.

The alternative is writing my own HOG-like based upon IMAGER in which case
whatever HOG_apply does with numbers of files won't matter.

I am not using HOG for automatic discrimination but for understanding and
manual discrimination.

Thanks for your efforts,

  - Jan

**Comment by mlampros** [comment]
I've converted the SimpleCV python function to Rcpp in the OpenImageR package. Everything related to HOG can be seen in the *OpenImageRheader.h* file and especially in the [lines 2211 to 2406](https://github.com/mlampros/OpenImageR/blob/master/inst/include/OpenImageRheader.h#L2211-L2406)
The function that will give an answer to your question about the orientation bins is the [hog_cpp()](https://github.com/mlampros/OpenImageR/blob/master/inst/include/OpenImageRheader.h#L2237-L2307)

**Comment by ecoquant** [comment]
Thanks much for your help.  However, I've decided for my purposes (studying changes in moss communities using digital photographs) direct access to the point gradient magnitudes and their directions is what I want.  I don't want any discretization.  For my purposes, that's throwing information away.  By having access to the magnitudes and directions I can create a conceptual spectrum on -pi to +pi with the strengths of the gradients as amplitudes.  And if I have two of those, I can compare them using all kinds of spectral comparison or density comparison techniques.
