### ISSUE TITLE
Metadata retention with rotateFixed function?

### ISSUE THREAD

**Issue by RlongWPZ** [mlampros/OpenImageR#23]
Please briefly describe your problem and what output you expect. If you have a question, you also have the option of <https://stackoverflow.com/> (but I'm flexible if it's not too complicated)

I'm using the "rotateFixed" function and am wondering if it maintains Jpeg metadata, specifically the "Date/Time created" fields? On rotated images I see correct "Date Created" information when viewing metadata on some platforms (e.g., Lightroom, Bridge), but have had others (e.g., the new Wildlife Insights camera trap platform) not correctly read the original/correct Date/Time metadata.

I'm not necessarily looking for a fix, but just to get confirmation if the code is meant to retain correct metadata after rotation. 

Please include a minimal reproducible example

Please give a brief description of the problem

Please add your Operating System (e.g., Windows10, Macintosh, Linux) and the R version that you use (e.g., 3.6.2)
I'm running a new installation of R and RStudio on a new MacBook Pro under OSx 12.1 Monterey.

If my package uses Python (via 'reticulate') then please add also the Python version (e.g., Python 3.8) and the 'reticulate' version (e.g., 1.18.0)

**Comment by mlampros** [comment]
hi @RlongWPZ,

the [OpenImageR::readImage](https://github.com/mlampros/OpenImageR/blob/master/R/read_image.R#L40-L43) uses internally the ```jpeg``` R package. In the ```jpeg::readJPEG(source, native = FALSE)``` the user has the option to also receive an image raster (with different attributes) by setting the parameter ```native``` to TRUE,

```R

# source file downloaded from: https://jpeg.org/jpegxt/

url = 'https://jpeg.org/images/jpegxt-home.jpg'

pth_JPEG = tempfile(pattern = '.jpg')
download.file(url = url, destfile = pth_JPEG)

new_pth_name = glue::glue("{pth_JPEG}.jpg")
file.rename(from = pth_JPEG, to = new_pth_name)

image_raster = OpenImageR::readImage(path = new_pth_name, native = TRUE)
str(image_raster)

attributes(image_raster)

image = OpenImageR::readImage(path = new_pth_name, native = FALSE)
str(image)

attributes(image)

r = OpenImageR::rotateFixed(image, 90)

OpenImageR::imageShow(r)

```

Therefore, any metadata related to your uploaded image can be retrieved using the ```OpenImageR::readImage``` function.
However, the [OpenImageR::rotateFixed](https://github.com/mlampros/OpenImageR/blob/master/R/open_image_rscript.R#L675-L701) can not hold or return any metadata (it calls internally Rcpp code).
Is your intention to attach metadata to the output of the ```OpenImageR::rotateFixed``` function (before saving the image to a file)?

**Comment by mlampros** [comment]
I think the [exifr](https://github.com/paleolimbot/exifr#installation) R package allows a user to retrieve the time created and modified of an image (you need Perl regarding the system requirements),

```R

url = 'https://jpeg.org/images/jpegxt-home.jpg'

pth_JPEG = tempfile(pattern = '.jpg')
download.file(url = url, destfile = pth_JPEG)

new_pth_name = glue::glue("{pth_JPEG}.jpg")
file.rename(from = pth_JPEG, to = new_pth_name)

metadat_jpeg = exifr::read_exif(path = new_pth_name)
metadat_jpeg

# # A tibble: 1 × 24
# SourceFile  ExifToolVersion FileName Directory FileSize FileModifyDate FileAccessDate FileInodeChange… FilePermissions FileType FileTypeExtensi… MIMEType JFIFVersion
# <chr>                 <dbl> <chr>    <chr>        <int> <chr>          <chr>          <chr>                      <int> <chr>    <chr>            <chr>    <chr>      
#   1 /tmp/Rtmpe…            12.2 .jpg43e… /tmp/Rtm…    17489 2022:03:02 08… 2022:03:02 08… 2022:03:02 08:0…          100664 JPEG     JPG              image/j… 1 1        
# # … with 11 more variables: ResolutionUnit <int>, XResolution <int>, YResolution <int>, ImageWidth <int>, ImageHeight <int>, EncodingProcess <int>,
# #   BitsPerSample <int>, ColorComponents <int>, YCbCrSubSampling <chr>, ImageSize <chr>, Megapixels <dbl>

```
Then to save the output image with the metadata you might have to use the [exiftool_call](https://github.com/paleolimbot/exifr/issues/12#issuecomment-601442449) function as described in an issue
