### ISSUE TITLE
Renaming function 'delationErosion' to 'dilationErosion' 

### ISSUE THREAD

**Issue by mirickmi** [mlampros/OpenImageR#24]
Hi,

thanks for this wonderful package. This is just a minor (terminology) issue but could you rename "delation" to "dilation"?

**Comment by mlampros** [comment]
I submitted the updated version to CRAN ('1.2.6'). The new function [dilationErosion()](https://mlampros.github.io/OpenImageR/reference/dilationErosion.html) [replaces the old one](https://github.com/mlampros/OpenImageR/blob/master/NEWS.md) ('delationErosion') and the 'delationErosion' will be entirely removed in version 1.3.0
