### ISSUE TITLE
supported image types are case sensitive

### ISSUE THREAD

**Issue by machadoams** [mlampros/OpenImageR#25]
Hi, 

I am trying to calculate hash values for JPG images, but `OpenImageR::readImage` is case sensitive and returns an error: *supported image types are .png, .jpeg, .jpg, .tiff (or .tif, .TIFF, .TIF)*

I understand that modifying the file extension would work, but perhaps the `readImage()` function could simply ignore case sensitive in the exception for the supported image types. For example:

```r
if (isTRUE(grepl(x = flag_type, pattern = c("jpeg|jpg"), ignore.case = TRUE))){
  img = jpeg::readJPEG(path)
}
```
System: R 4.2.2 on x86_64-pc-linux-gnu. OpenImageR_1.2.7 and jpeg_0.1-10.

Thanks for the great work.

**Comment by mlampros** [comment]
hi @machadoams give me some time and I'll push the changes to the repository to address this issue

**Comment by mlampros** [comment]
@machadoams I added the [verify_image_extension()](https://github.com/mlampros/OpenImageR/blob/master/R/read_image.R#L32-L43) function. Can you install the Github version using

```R

remotes::install_github('mlampros/OpenImageR')

```

and let me know if it works for you too, so that I can submit the updated version to CRAN?
Thank you for making me aware of this issue.

**Comment by mlampros** [comment]
I assume it works for you. I'll proceed and submit the new version to CRAN. Feel free to re-open the issue if the code does not work as expected

**Comment by machadoams** [comment]
Hi @mlampros 

It's working now! Thank you for taking the time to work on this.
