### ISSUE TITLE
imagehash

### ISSUE THREAD

**Issue by JohannesBuchner** [mlampros/OpenImageR#5]
Hi! Cool to see imagehash re-implemented in R.  I was wondering if you would consider adding a reference back to the original project. You might also want to check the latest version, we fixed some bugs (see Changelog). Cheers!

**Comment by mlampros** [comment]
I'm sorry for the late reply. I've added a reference in the [inst folder](https://github.com/mlampros/OpenImageR/blob/master/inst/COPYRIGHTS) and in the [DESCRIPTION file](https://github.com/mlampros/OpenImageR/blob/master/DESCRIPTION) (Authors) as defined in [Writing R extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html) and is the case for an R-package. I'm sorry if I sound silly, do you think I have also to include the reference/copyrights field somewhere else?
I'll look onto the dhash bug and fix the corresponding R-function with in the next few days. Thanks for making me aware of it.

**Comment by JohannesBuchner** [comment]
I am not a lawyer, but I think it's fine. You could add a link to https://github.com/JohannesBuchner/imagehash . Some people put the license/copyright in the file directly, because BSD works filewise, not project wise and files tend to get copied. Don't worry too much about it :)

**Comment by mlampros** [comment]
I think you are right, I'll add at the top of the [https://github.com/mlampros/OpenImageR/blob/master/src/image_hashing.cpp](https://github.com/mlampros/OpenImageR/blob/master/src/image_hashing.cpp) file the following commented lines,

```R

/*
* Copyright (c) 2013-2016, Johannes Buchner
* All rights reserved.
* https://github.com/JohannesBuchner/imagehash
*/

```

and I'll do the same for the Hog-features (SimpleCV python package). Is it ok?

**Comment by JohannesBuchner** [comment]
Sure, thanks!

**Comment by mlampros** [comment]
I close the issue as,

* I updated the source files (image_hashing.cpp, hog_features.cpp) adding the copyright holders
* I fixed the bug in the dhash function
* I uploaded version 1.0.5 of the package to CRAN

**Comment by JohannesBuchner** [comment]
Thanks!
